version: "2"
run:
  timeout: 5m
linters:
  enable:
    - govet
    - errcheck
    - staticcheck
issues:
  max-issues-per-linter: 0
  max-same-issues: 0

# Optional: enable or disable additional linters as needed
# linters:
#   enable:
#     - gocritic
#     - revive
