# GoReleaser configuration for e5s SPIRE mTLS library
# Automates building, archiving, Docker images, and releasing to GitHub

version: 2

before:
  hooks:
    # Ensure dependencies are up to date
    - go mod tidy
    - go mod verify

builds:
  # Example server binary (for Docker and local use)
  - id: example-server
    main: ./examples/basic-server
    binary: e5s-example-server
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}
    flags:
      - -trimpath

  # Example client binary (for Docker and local use)
  - id: example-client
    main: ./examples/basic-client
    binary: e5s-example-client
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}
    flags:
      - -trimpath

  # e5s CLI tool for SPIFFE ID management and config validation
  - id: e5s-cli
    main: ./cmd/e5s
    binary: e5s
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}
    flags:
      - -trimpath

# Docker images for examples (enables `helm install` without Go)
dockers:
  - ids: [example-server]
    image_templates:
      - "ghcr.io/sufield/e5s-demo-server:{{ .Tag }}"
      - "ghcr.io/sufield/e5s-demo-server:latest"
    dockerfile: Dockerfile.server
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title=e5s-demo-server"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/amd64"
    extra_files:
      - go.mod
      - go.sum

  - ids: [example-server]
    image_templates:
      - "ghcr.io/sufield/e5s-demo-server:{{ .Tag }}-arm64"
    dockerfile: Dockerfile.server
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title=e5s-demo-server"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/arm64"
    goarch: arm64
    extra_files:
      - go.mod
      - go.sum

  - ids: [example-client]
    image_templates:
      - "ghcr.io/sufield/e5s-demo-client:{{ .Tag }}"
      - "ghcr.io/sufield/e5s-demo-client:latest"
    dockerfile: Dockerfile.client
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title=e5s-demo-client"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/amd64"
    extra_files:
      - go.mod
      - go.sum

  - ids: [example-client]
    image_templates:
      - "ghcr.io/sufield/e5s-demo-client:{{ .Tag }}-arm64"
    dockerfile: Dockerfile.client
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title=e5s-demo-client"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/arm64"
    goarch: arm64
    extra_files:
      - go.mod
      - go.sum

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      # Include important files in release archives
      - README.md
      - LICENSE
      - SECURITY.md
      - docs/**/*
      - examples/**/*

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  algorithm: sha256

# Sign release artifacts using Cosign (keyless signing via Sigstore/Fulcio)
# Provides cryptographic verification of release artifacts for supply chain security
# Improves OpenSSF Scorecard Signed-Releases score
signs:
  - cmd: cosign
    artifacts: checksum
    signature: "${artifact}.sig"
    certificate: "${artifact}.pem"
    args:
      - "sign-blob"
      - "--yes"
      - "--output-signature=${signature}"
      - "--output-certificate=${certificate}"
      - "${artifact}"
    output: true

changelog:
  use: github
  sort: asc
  abbrev: 7
  groups:
    - title: "Security"
      regexp: "^.*?(sec|security|vuln).*?:"
      order: 0
    - title: "Features"
      regexp: "^.*?(feat|feature).*?:"
      order: 1
    - title: "Bug Fixes"
      regexp: "^.*?(fix|bug).*?:"
      order: 2
    - title: "Documentation"
      regexp: "^.*?doc.*?:"
      order: 3
    - title: "Dependencies"
      regexp: "^.*?(dep|deps|dependenc).*?:"
      order: 4
    - title: "Other"
      order: 999
  filters:
    exclude:
      - "^test:"
      - "^chore:"
      - "^ci:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: sufield
    name: e5s
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## e5s {{ .Tag }} - SPIRE mTLS Library Release

    This release includes the e5s library, CLI tool, utilities, Docker images, and Helm chart for demonstrations.

    ### Installation

    **For Go developers (library usage):**
    ```bash
    go get github.com/sufield/e5s@{{ .Tag }}
    ```

    **For CLI tool (SPIFFE ID management and config validation):**
    ```bash
    # Download pre-built binaries from release assets
    # Or install from source:
    go install github.com/sufield/e5s/cmd/e5s@{{ .Tag }}

    # Usage examples:
    e5s spiffe-id k8s example.org default api-client
    e5s discover pod my-pod
    e5s validate e5s.yaml
    ```

    **For trying examples (Docker images):**
    ```bash
    # Pull pre-built images
    docker pull ghcr.io/sufield/e5s-demo-server:{{ .Tag }}
    docker pull ghcr.io/sufield/e5s-demo-client:{{ .Tag }}
    ```

    **For Kubernetes deployments (Helm chart):**
    ```bash
    # Clone the repository and install the chart
    git clone https://github.com/sufield/e5s.git
    cd e5s
    git checkout {{ .Tag }}
    helm install e5s-demo ./chart/e5s-demo \
      --set server.image.tag={{ .Tag }} \
      --set client.image.tag={{ .Tag }}
    ```

    **For utilities (download pre-built binaries below):**
    - **e5s**: CLI for SPIFFE ID management and configuration validation

    See the [documentation](https://github.com/sufield/e5s/tree/{{ .Tag }}/docs) for usage examples.
  footer: |
    ---

    **Full Changelog**: https://github.com/sufield/e5s/compare/{{ .PreviousTag }}...{{ .Tag }}

    ### Docker Images

    Multi-arch images (amd64/arm64) are available at:
    - Server: `ghcr.io/sufield/e5s-demo-server:{{ .Tag }}`
    - Client: `ghcr.io/sufield/e5s-demo-client:{{ .Tag }}`

    ### Verification

    **SHA256 Checksums:**
    ```bash
    sha256sum -c {{ .ProjectName }}_{{ .Version }}_SHA256SUMS
    ```

    **Cryptographic Signatures (Cosign):**

    This release is cryptographically signed using Cosign with keyless signing (Sigstore/Fulcio).
    Verify the checksum file signature:

    ```bash
    # Install Cosign
    go install github.com/sigstore/cosign/cmd/cosign@latest

    # Verify the checksum file
    cosign verify-blob \
      --certificate {{ .ProjectName }}_{{ .Version }}_SHA256SUMS.pem \
      --signature {{ .ProjectName }}_{{ .Version }}_SHA256SUMS.sig \
      --certificate-identity-regexp="https://github.com/{{.Env.GITHUB_REPOSITORY}}/" \
      --certificate-oidc-issuer="https://token.actions.githubusercontent.com" \
      {{ .ProjectName }}_{{ .Version }}_SHA256SUMS
    ```

    The signature files (`.sig` and `.pem`) are included in the release assets for supply chain verification.

    ### Support

    - 📖 Documentation: https://github.com/sufield/e5s/tree/{{ .Tag }}/docs
    - 🐛 Issues: https://github.com/sufield/e5s/issues
    - 🔒 Security: See [SECURITY.md](https://github.com/sufield/e5s/blob/{{ .Tag }}/.github/SECURITY.md)

    Thank you for using e5s!

# Source code archives
source:
  enabled: true
  name_template: "{{ .ProjectName }}_{{ .Version }}_source"
  format: tar.gz

# Announce releases (disabled for now, can enable for Slack/Discord/etc)
announce:
  skip: true

# Metadata
metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"
