name: Bug Report
description: Report a bug or unexpected behavior in e5s
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out the information below to help us diagnose and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior.
      placeholder: |
        1. Initialize e5s with...
        2. Configure SPIRE with...
        3. Run the client/server...
        4. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: I expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Instead, I saw...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs and Error Messages
      description: Include relevant logs, error messages, or stack traces.
      placeholder: |
        Paste logs here...
      render: shell
    validations:
      required: false

  - type: input
    id: go-version
    attributes:
      label: Go Version
      description: Run `go version` to get this information.
      placeholder: "go version go1.25.3 linux/amd64"
    validations:
      required: true

  - type: input
    id: e5s-version
    attributes:
      label: e5s Version
      description: Which version of e5s are you using?
      placeholder: "v0.1.0 or commit hash"
    validations:
      required: true

  - type: input
    id: spire-version
    attributes:
      label: SPIRE Version
      description: Run `spire-server --version` or `spire-agent --version`.
      placeholder: "v1.10.0"
    validations:
      required: false

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What OS are you running on?
      options:
        - Linux
        - macOS
        - Windows
        - Docker/Container
        - Kubernetes
        - Other
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: Additional environment information (OS version, Docker version, Kubernetes version, etc.)
      placeholder: |
        - OS: Ubuntu 22.04
        - Kernel: 6.8.0-87-generic
        - Docker: 27.0.3
        - Kubernetes: v1.30.0
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or information about the problem.
    validations:
      required: false

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checklist
      description: Please verify the following before submitting.
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have included all relevant information above
          required: true
        - label: I have redacted any sensitive information (API keys, credentials, etc.)
          required: true
