name: Feature Request
description: Suggest a new feature or enhancement for e5s
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! Please provide as much detail as possible to help us understand your proposal.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm frustrated when... / It would be helpful if...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: I would like e5s to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: I've considered... / I currently work around this by...
    validations:
      required: false

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your specific use case. How would this feature help you?
      placeholder: |
        My application needs to...
        This would help me...
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: Example Code or API
      description: If applicable, provide example code showing how you'd like to use this feature.
      placeholder: |
        ```go
        // Example of proposed API
        client, err := e5s.NewClient(...)
        ```
      render: go
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve my workflow
        - High - Blocking my use case
        - Critical - Cannot use e5s without this
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of e5s does this feature relate to?
      options:
        - Client API
        - Server API
        - SPIRE Integration
        - Configuration
        - Error Handling
        - Documentation
        - Examples
        - Testing
        - Performance
        - Other
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or links about the feature request.
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to help implement this feature?
      options:
        - label: I would be willing to submit a PR for this feature
          required: false
        - label: I would be willing to help test this feature
          required: false

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checklist
      description: Please verify the following before submitting.
      options:
        - label: I have searched existing issues and discussions to avoid duplicates
          required: true
        - label: This feature aligns with the project's goals and scope
          required: true
        - label: I have provided sufficient detail for the maintainers to evaluate this request
          required: true
