# Helmfile for SPIRE dev environment on Minikube
# This orchestrates SPIRE server and agent deployment
# Usage: helmfile -e dev apply

---
environments:
  dev:
    values:
      - environment: dev
      - cluster: minikube

---
repositories:
  - name: spiffe
    url: https://spiffe.github.io/helm-charts-hardened/

releases:
  # SPIRE (combined server + agent)
  - name: spire
    namespace: spire-system
    createNamespace: true
    chart: spiffe/spire
    version: 0.27.0
    values:
      - values-minikube.yaml
      - values-minikube-secrets.yaml
    wait: true
    timeout: 300
