# mtls-server-image.yaml - Production/Demo deployment using container image
#
# This is the recommended approach for:
# - Production deployments
# - Conference demos and presentations
# - Automated CI/CD pipelines
#
# Prerequisites:
#   1. Build and push the container image:
#      docker build -t your-registry/mtls-server:latest -f examples/zeroconfig-example/Dockerfile .
#      docker push your-registry/mtls-server:latest
#
#   2. Update the image field below with your registry
#
#   3. Register the server workload with SPIRE (see examples/README.md)
#
# Usage:
#   kubectl apply -f examples/mtls-server-image.yaml
#   kubectl wait --for=condition=Ready deploy/mtls-server --timeout=60s
#   kubectl port-forward svc/mtls-server 8443:8443

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mtls-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mtls-server
  template:
    metadata:
      labels:
        app: mtls-server
    spec:
      # Pod-level security context
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534   # Standard Debian "nobody" user
        fsGroup: 65534     # Helps with socket access on hostPath
      # Disable service account token mounting (not needed for this demo)
      automountServiceAccountToken: false
      volumes:
        - name: spire-socket
          # If your SPIRE agent uses a different public socket directory, change this to match.
          # This path matches the default SPIRE Helm chart configuration.
          hostPath:
            path: /tmp/spire-agent/public
            type: Directory
      containers:
        - name: mtls-server
          # TODO: Replace with your container registry
          image: ghcr.io/yourorg/mtls-server:latest
          imagePullPolicy: Always
          # Container-level security context
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65534
            capabilities:
              drop:
                - ALL
          ports:
            - name: https
              containerPort: 8443
          volumeMounts:
            - name: spire-socket
              mountPath: /spire-socket
              readOnly: true
          # Readiness probe: TCP check with longer delay to allow server startup
          # For production demos, consider using exec probe for accurate mTLS verification:
          #   exec:
          #     command: ["sh","-c","curl -sk https://localhost:8443/health | grep -q 'ok'"]
          readinessProbe:
            tcpSocket:
              port: 8443
            initialDelaySeconds: 5   # Increased from 2s to allow server startup
            periodSeconds: 5
          # Resource limits for production
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"   # Increase to 300m if throttling on small clusters
          # Optional: Environment variables (zero-config auto-detects these)
          # Can be omitted entirely to rely on autodetection.
          # env:
          #   - name: SPIFFE_ENDPOINT_SOCKET
          #     value: "unix:///spire-socket/api.sock"
          #   - name: SERVER_ADDRESS
          #     value: ":8443"
---
apiVersion: v1
kind: Service
metadata:
  name: mtls-server
  namespace: default
spec:
  selector:
    app: mtls-server
  ports:
    - name: https
      port: 8443
      targetPort: 8443
