# mtls-server.yaml - Zero-config mTLS server deployment with SPIRE Workload API access
#
# This Deployment runs the zero-config mTLS server with access to the SPIRE agent socket.
# The socket is mounted from the Minikube host node into the pod.
# The zero-config server auto-detects the socket and trust domain - no manual configuration needed!
#
# Usage:
#   See examples/README.md for complete deployment guide

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mtls-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mtls-server
  template:
    metadata:
      labels:
        app: mtls-server
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534  # nobody user
        fsGroup: 65534
      volumes:
        - name: spire-socket
          hostPath:
            path: /tmp/spire-agent/public   # path on the Minikube node (matches chart defaults)
            type: Directory
      containers:
        - name: mtls-server
          image: debian:bookworm-slim
          command: ["sleep", "infinity"]  # Keep pod alive for binary copy
          env:
            - name: SPIFFE_ENDPOINT_SOCKET
              value: "unix:///spire-socket/api.sock"
            - name: SERVER_ADDRESS
              value: ":8443"
          volumeMounts:
            - name: spire-socket
              mountPath: /spire-socket
              readOnly: true
          ports:
            - containerPort: 8443
          securityContext:
            allowPrivilegeEscalation: false
---
apiVersion: v1
kind: Service
metadata:
  name: mtls-server
  namespace: default
spec:
  selector:
    app: mtls-server
  ports:
    - name: https
      port: 8443
      targetPort: 8443
