# mtls-server.yaml - Development deployment for local testing
#
# This is the development/testing approach using kubectl cp to copy a locally-built binary.
# For production or demo use, see mtls-server-image.yaml instead.
#
# Prerequisites:
#   1. Build the server binary: go build -o bin/mtls-server ./examples/zeroconfig-example
#   2. Deploy SPIRE infrastructure: make minikube-up
#   3. Register workloads with SPIRE (see examples/README.md)
#
# Usage:
#   kubectl apply -f examples/mtls-server.yaml
#   kubectl cp bin/mtls-server POD:/tmp/mtls-server
#   kubectl exec POD -- chmod +x /tmp/mtls-server
#   kubectl exec -it POD -- /tmp/mtls-server
#
# See examples/README.md for complete deployment guide

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mtls-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mtls-server
  template:
    metadata:
      labels:
        app: mtls-server
    spec:
      # Pod-level security context
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        fsGroup: 65532
      volumes:
        - name: spire-socket
          hostPath:
            path: /tmp/spire-agent/public
            type: Directory
      containers:
        - name: mtls-server
          image: debian:bookworm-slim
          command: ["sleep", "infinity"]  # Keep pod alive for binary copy
          # Container-level security context
          # NOTE: readOnlyRootFilesystem not set to allow kubectl cp to /tmp
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 65532
            capabilities:
              drop:
                - ALL
          ports:
            - name: https
              containerPort: 8443
          volumeMounts:
            - name: spire-socket
              mountPath: /spire-socket
              readOnly: true
          # Optional: Environment variables (zero-config auto-detects these)
          env:
            - name: SPIFFE_ENDPOINT_SOCKET
              value: "unix:///spire-socket/api.sock"
            - name: SERVER_ADDRESS
              value: ":8443"
          # TCP readiness probe - useful for checking if server started
          readinessProbe:
            tcpSocket:
              port: 8443
            initialDelaySeconds: 2
            periodSeconds: 5
          # Resource limits
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: mtls-server
  namespace: default
spec:
  selector:
    app: mtls-server
  ports:
    - name: https
      port: 8443
      targetPort: 8443
