# test-client.yaml - Test client pod with SPIRE Workload API access
#
# This Deployment creates a client pod that can obtain SPIFFE identities
# and make mTLS requests to the mtls-server.
#
# Usage (quick copy/paste):
#   kubectl apply -f examples/test-client.yaml
#   kubectl wait --for=condition=Available deploy/test-client --timeout=60s
#   POD=$(kubectl get pod -l app=test-client -o jsonpath='{.items[0].metadata.name}')
#   kubectl exec -it "$POD" -- bash
#
# Inside the pod (optional tools for demos):
#   apt-get update && apt-get install -y ca-certificates curl git && update-ca-certificates
#
# See examples/README.md for complete guide and client code examples

apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-client
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-client
  template:
    metadata:
      labels:
        app: test-client
    spec:
      # Disable service account token mounting (not needed for this demo)
      automountServiceAccountToken: false
      # Pod-level security context
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534   # Standard Debian "nobody" user
        fsGroup: 65534     # Helps with socket access on hostPath
        seccompProfile:
          type: RuntimeDefault   # Additional security with no demo downside
      volumes:
        - name: spire-socket
          # Matches the SPIRE Helm chart default public socket directory.
          # Change this if your agent uses a different path.
          hostPath:
            path: /tmp/spire-agent/public
            type: Directory
      containers:
        - name: test-client
          image: golang:1.25
          command: ["sleep", "infinity"]
          # Container-level security context
          # NOTE: readOnlyRootFilesystem not set for development flexibility
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 65534
            capabilities:
              drop:
                - ALL
          env:
            - name: SPIFFE_ENDPOINT_SOCKET
              value: "unix:///spire-socket/api.sock"
          volumeMounts:
            - name: spire-socket
              mountPath: /spire-socket
              readOnly: true
          # Resource limits
          # CPU bump helps with in-pod 'go run' compilation
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "300m"   # Increased from 200m for faster builds
