# Helmfile for SPIRE dev environment on Minikube
# This orchestrates SPIRE server and agent deployment
# Usage: helmfile -e dev apply
#
# Optional components (set environment variables to enable):
# - Falco: ENABLE_FALCO=true helmfile -e dev apply

---
environments:
  dev:
    values:
      - environment: dev
      - cluster: minikube

---
repositories:
  - name: spiffe
    url: https://spiffe.github.io/helm-charts-hardened/
  - name: falcosecurity
    url: https://falcosecurity.github.io/charts

releases:
  # SPIRE (combined server + agent)
  - name: spire
    namespace: spire-system
    createNamespace: true
    chart: spiffe/spire
    version: 0.27.0
    values:
      - values-minikube.yaml
      - values-minikube-secrets.yaml
    wait: true
    timeout: 300

  # Falco (optional runtime security monitoring)
  # Enable with: ENABLE_FALCO=true helmfile -e dev apply
  - name: falco
    namespace: falco
    createNamespace: true
    chart: falcosecurity/falco
    version: 4.19.4
    condition: enableFalco
    values:
      - values-falco.yaml
    wait: true
    timeout: 300
    installed: {{ env "ENABLE_FALCO" | default "false" }}
